#2415 Added PetalBot
browscap/browscap pull request #2420
Opened 2021-01-11 12:52 UTC by skoshelev

Hi. I added the PetalBot to the crawlers list, could you please check my PR and give me feedback

2021-01-11 13:01 UTC, asgrim approved these changes
@mimmi20 think the CS issue can be ignored here? Probably needs main branch looking at separately.

2021-01-11 13:07 UTC, mimmi20 requested changes

2021-01-11 13:07 UTC, mimmi20 commented on tests/issues/issue-2415.php
> +?>
Please remove the closing PHP-Tags, It is not required for PHP-Files. Please add a single empty line at the end of the file.

2021-01-11 13:07 UTC, mimmi20 commented on resources/user-agents/crawlers/search-engines/petalbot.json
> +			"Comment": "PetalBot (PC)"
Please fix the identification.

2021-01-11 13:07 UTC, mimmi20 commented on resources/user-agents/crawlers/search-engines/petalbot.json
> +          "match": "Mozilla\/5.0 (Linux; Android 7.0;) AppleWebKit\/537.36 (KHTML, like Gecko) Mobile Safari\/537.36 (compatible; PetalBot;+https:\/\/aspiegel.com\/petalbot)",
Please make this rule more generic and not escape the Slashes.

Something like "Mozilla/5.0 (Linux; Android 7.*) AppleWebKit/* (KHTML, like Gecko) *Safari/* (compatible; PetalBot*"

We also have placeholder for platforms. Please look into the rules for the Chrome/Android, how to use.

2021-01-11 13:07 UTC, mimmi20 commented on resources/user-agents/crawlers/search-engines/petalbot.json
> +          "match": "Mozilla\/5.0 (compatible; PetalBot;+https:\/\/aspiegel.com\/petalbot)",
Please make this rule more generic and not escape the Slashes.

Something like "Mozilla/5.0 (compatible; PetalBot*"

2021-01-11 13:07 UTC, mimmi20 commented on resources/user-agents/crawlers/search-engines/petalbot.json
> +          "match": "Mozilla\/5.0 (compatible; PetalBot;+https:\/\/aspiegel.com\/petalbot)",
Please add a test for this useragent too.

2021-01-12 07:45 UTC, skoshelev commented
Hi @mimmi20. Thank you for your review, I made suggested changes

2021-01-12 08:14 UTC, mimmi20 approved these changes

2021-01-12 08:15 UTC, merged