Feature/2534 update apple platform versions
browscap/browscap pull request #2535
Opened 2021-11-12 07:50 UTC by paulrutter

#2534 Update Apple platform versions
- Added 'OSX_dynamic' and 'OSX_10_16' for Mac OS
- Added 'ipadOS_15_0' / 'ipadOS_15_2'
- Added 'iOS_A_15_0' / 'iOS_A_15_2'
- Added platform to the browsers that it runs on, also including the "generic" platforms to have better coverage for future versions (when the useragent remains the same)

@asgrim @mimmi20 
I did an attempt to add the recent Apple platform versions to browscap.
Also added a "dynamic" OSX item in platforms.json

I still don't exactly understand why those "dynamic" platforms are not added to all browsers, since that would help recognizing future versions which are not specified exactly in "platforms.json". I did that now for the Apple related platforms, but not sure if that's right. Can you help me on this logic? Maybe i'm misunderstanding and those generic ones shouldn't be added?

2021-11-12 08:22 UTC, paulrutter commented
Also, can you help determine which unit test if failing? 
I cannot see that in the logs: https://github.com/browscap/browscap/runs/4187437561?check_suite_focus=true

2021-11-12 12:14 UTC, mimmi20 requested changes

2021-11-12 12:14 UTC, mimmi20 commented on resources/user-agents/browsers/chrome/chrome-ios-73-on.json
> +            "iOS_A_15_2", "iOS_A_15_1", "iOS_A_15_0", "iOS_A_14_2", "iOS_A_14_1", "iOS_A_14_0",
Please add the new versions (15.x) on a new line

2021-11-12 12:14 UTC, mimmi20 commented on resources/user-agents/browsers/chrome/chrome-ios-73-on.json
> +            "ipadOS_15_2", "ipadOS_15_1", "ipadOS_15_0", "ipadOS_14_2", "ipadOS_14_1", "ipadOS_14_0",
Please add the new versions (15.x) on a new line

2021-11-12 12:14 UTC, mimmi20 commented on resources/user-agents/browsers/mobile-safari/mobile-safari-generic.json
> +            "iOS_A_15_2", "iOS_A_15_1", "iOS_A_15_0", "iOS_A_14_2", "iOS_A_14_1", "iOS_A_14_0",
Please add the new versions (15.x) on a new line

2021-11-12 12:22 UTC, paulrutter commented
I fixed the comments, but i think that won't help solve the unit test issue.
Can you take a look at my question here? https://github.com/browscap/browscap/pull/2535#issuecomment-966912527

2021-11-12 14:09 UTC, mimmi20 approved these changes

2021-11-12 14:10 UTC, paulrutter commented
Thanks for approving @mimmi20, but since the unit tests still fail i don't think we should merge.
I need more info on the "dynamic" platforms, as mentioned earlier.

2021-11-12 17:11 UTC, mimmi20 commented
"dynamic" platforms only work, if the platform version matches the browser version.

2021-11-12 17:14 UTC, mimmi20 commented
The Build is failing since May. Idont think your changes caused this.

2021-11-15 07:52 UTC, paulrutter commented
> The Build is failing since May. Idont think your changes caused this.

I will try to fix the unit tests first, so we can actually see what my changes did to existing functionality.

2021-11-15 11:36 UTC, mimmi20 requested changes

2021-11-15 11:36 UTC, mimmi20 commented on resources/user-agents/browsers/chrome/chrome-generic.json
> +            "OSX_11_0", "OSX_11_1",
Please change the ordering. Please write `"OSX_11_1", "OSX_11_0"` (like you did in the Chrome file). Please change it in other files too.

2021-11-15 11:36 UTC, mimmi20 commented on resources/user-agents/browsers/mobile-safari/mobile-safari-15-0.json
> +  "versions": [14],
Please change the version to 15

2021-11-15 11:36 UTC, mimmi20 commented on resources/user-agents/browsers/mobile-safari/mobile-safari-14-0.json
> +  "versions": ["14.0", "14.1", "14.2", "14.3", "14.4", "14.5", "14.6", 14],
Please change the order of versions. Please write the highest first. The version "14.0" is not needed, as it the same as version "14". Also change the file name to `mobile-safari-14-x.json`.

2021-11-15 11:36 UTC, mimmi20 commented on resources/user-agents/browsers/mobile-safari/mobile-safari-13-0.json
> +  "versions": ["13.1", 13],
Please change the filename to `mobile-safari-13-x.json`.

2021-11-15 11:36 UTC, mimmi20 commented on resources/user-agents/browsers/safari/safari-15-0.json
> +    "versions": ["15.0", 15],
These two versions are the same, as the Zero will be added automatically, if a `#MINORVER#` placeholder is there.

2021-11-15 11:36 UTC, mimmi20 commented on tests/BrowscapTest/Generator/Helper/BuildHelperTest.php
> +            $writerCollection->expects(static::any())
Please keep the indent

2021-11-15 12:09 UTC, paulrutter commented
@mimmi20 I managed to get the unit tests running again, by reverting a change in https://github.com/browscap/browscap/pull/2535/files#diff-cebc14b7503943d2278cbaf4fe86c60f57707b619511f54041399054709dd28d.

Now i had to fix few other unit tests that were added already, but didn't succeed.
I've tried, to my best knowledge, to add the new Apple platforms:

* Mac OS Big sur (11) and Monterey (12), 10.x range is no longer used although 10.16 was used at some point
* iOS 14.0 / 14.8 and 15.0 / 15.2 (which is in beta)
* iPad OS 15.0 / 15.2, didn't add 14.3 / 14.8 as i wasn't sure it was used

I also added Safari 15 specifically, as that is shipped with Mac Monterey. 
In the readme, i updated the badge for the CI, which was no longer ok.

@mimmi20 i processed your latest comments. Can you re-review and merge if you think it's ok now?
The code coverage report still seems a bit off, but not sure how to resolve that.

2021-11-15 12:12 UTC, mimmi20 approved these changes

2021-11-16 07:54 UTC, paulrutter commented
@mimmi20 can you merge and release a new browscap version if you're ok with the changes?

2021-11-16 19:39 UTC, mimmi20 commented
@paulrutter I may be able to merge, but not to release.
@asgrim Could you merge and release?

2021-11-17 08:20 UTC, merged

2021-11-17 08:23 UTC, asgrim commented
Yep, thank you @paulrutter - appreciate the effort and fixing up those tests :metal:

2021-11-17 08:47 UTC, paulrutter commented
@asgrim do we need to trigger something for http://browscap.org/ as well?

2021-11-17 08:49 UTC, asgrim commented
Yes, waiting for Dependabot

@mimmi20 FYI the release procedure is at https://github.com/browscap/browscap/wiki/Public-release-procedure :) I believe you should be able to do most of it now

2021-11-17 09:29 UTC, asgrim commented
@paulrutter looks like it is up now :+1:

2021-11-17 09:30 UTC, paulrutter commented
Yes, great!

2021-11-17 18:03 UTC, willyaranda commented
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15`

is incorrectly detected, as does not match. Changing `Version/15.1` for `Version/15.0` does match and get the major version properly

2021-11-17 20:29 UTC, paulrutter commented
Hmm i wasn't aware of safari 15.1 was already released. We might add that as well.

2021-11-18 02:11 UTC, paulrutter commented
Created https://github.com/browscap/browscap/pull/2536 @willyaranda

2025-09-15 08:06 UTC, AnuarT79 commented
Obvious

2025-09-15 08:08 UTC, AnuarT79 commented on resources/user-agents/browsers/chrome/chrome-generic.json
> +            "OSX_11_0", "OSX_11_1",
> Please change the ordering. Please write `"OSX_11_1", "OSX_11_0"` (like you did in the Chrome