Added missing versions
browscap/browscap pull request #2542
Opened 2021-11-26 17:48 UTC by willyaranda

for Opera, Yabrowser, HuaweiBrowser, Firefox on iOS, Edge on Android, Electron…

2021-11-26 19:51 UTC, mimmi20 requested changes
Please add some tests for these versions

2021-12-01 10:43 UTC, mimmi20 approved these changes

2021-12-01 10:48 UTC, merged

2021-12-01 10:49 UTC, asgrim commented
Thank you @willyaranda and @mimmi20

2021-12-01 14:57 UTC, paulrutter commented
Released new browscap-java version 1.3.11 as well, which contains these changes 👍